### ISSUE TITLE
Add a backup script to the postgres image

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/errorreports#16]
As a developer I want to easily take backups of the database by running a `backup` command in the database.

This [cookie-cutter](https://cookiecutter-django.readthedocs.io/en/latest/docker-postgres-backups.html) project does something like this. The key parts that we can base our solution on is using [a custom postgres](https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/postgres) image that simply adds a basic backup script that calls `pg_dump`.

**Comment by martyngigg** [comment]
@Mantid-Matthew @DanielMurphy22 I think it would be great if we could look at this in maintenance. I've created mantidproject/reports#27  to do something similar for the usage reports. If we could workout sharing code that would be even better as there's so much common between these two projects.

**Comment by DavidFair** [comment]
Done in #21
